package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAndPackage'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAndPackage")) {
    check(buildNumberPattern == "5.0.%build.counter%") {
        "Unexpected option value: buildNumberPattern = $buildNumberPattern"
    }
    buildNumberPattern = "99.0.%build.counter%"
}
